### PR TITLE
Remove legacy Java CLI tool support

### PR DESCRIPTION
**Pull request by ches**
[Amazon's official aws-cli Python tool][aws-cli] has become full-featured and the Java tools are now treated as legacy in modern AWS official docs.

Even though aws-cli has good support for multiple account profiles (thanks a good deal to boto), I still believe awsenv is a relevant project because tools and libraries in other languages almost ubiquitously support the `AWS_` environment variables made conventional in the days of the Java tools, while they might not now or ever directly support aws-cli's INI file configuration because there is no promise that it's stable or should be used directly. I work with some tools like this and thus still need to switch environment variables, keypairs, etc. in my shell sessions. Plus aws-cli *does* support reading settings from the environment variables also, so awsenv can actually drive aws-cli's operation as an alternative to the native multiple profile support.

So, I'd like to make some improvements to awsenv that help it fit better in the new world of aws-cli. I have a few in mind, but first thing's first: ditch these outdated vendored copies of the Java tools—

1. They're long outdated.
2. They're a trust issue, users need to trust that the binaries provided through this repo are unmodified.
3. They make the repo huge to clone, compared to what it should be for small shell scripts (unfortunately repo size won't immediately and completely be helped retroactively, but at least we can offer tagged release tarballs as a quicker installation option).
4. They're largely obsolete now as aws-cli is the current preferred tool.

This changeset removes the binaries from the repo, and the function for setting the `X_HOME` env vars for each tool.

[aws-cli]: https://github.com/aws/aws-cli

### CODE REVIEW

**Comment by michaelcontento** [comment]
Thanks for this PR! 

Yes, aws-cli is now the way to go. Honestly I don't use AWS currently that much and haven't used this project for a long time now. But I'm very happy to accept PR's like this - thank you very much :)

As you are a more active user, we can drop `awsenv rehash` too, right?

And I've created a new tag 0.3.0 and we could add a new installation command like:

    $ curl -L https://github.com/michaelcontento/awsenv/archive/0.3.0.tar.gz \
         | tar xz && mv awsenv-* $HOME/.awsenv

What's your opinion about this?

**Comment by ches** [comment]
Ah yes, having long ago disabled the Java tools support locally before actually submitting the change, I don't think I've ever once used `awsenv rehash` and totally overlooked it :smile:  I can send a PR to clean that up too if you like.

About the installation command, I wonder if we can devise a workflow where untar can be done in-place so that you could update to newer versions over time the same way without disrupting your personal stuff in `~/.awsenv/envs`?

**Comment by michaelcontento** [comment]
It would be possible to clean up the git history and remove all binary files from this repo. Negative aspect of this would be a rewritten history :-| 

But I'm open for such a harsh solution, as it would make the update process pretty easy (`git pull` and you're done). What do you think? A more complex solution for the sake of a true/pure git history?

**Comment by ches** [comment]
I'm game for the history surgery. If it were a very active project, having everyone re-clone could be pretty painful. But, GitHub shows three forks—hopefully there won't be a serious revolt :grin:

**Comment by michaelcontento** [comment]
History has been rewritten. Prepare for the pitchfork mob! :joy:

**Pull request merged**
